name: Build and Push Docker Image

on:
  schedule: 
    - cron: '0 0 * * Mon'
  workflow_dispatch:

jobs:
  docker_hub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Hexo and get Hexo latest version
        run: |
          npm install -g hexo-cli hexo-server
          mkdir tmp_hexo && cd tmp_hexo
          hexo init
          npm list hexo --depth=0
          HEXO_VERSION=$(npm view hexo version)
          echo "Hexo version is $HEXO_VERSION"
          echo "HEXO_VERSION=$HEXO_VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if Hexo version has changed
        id: hexo_version_check
        run: |
          # Attempt to pull the image. If it fails, the version has changed or the image doesn't exist
          if ! docker pull ${{ secrets.DOCKER_USERNAME }}/hexo:${{ env.HEXO_VERSION }}; then
            echo "Hexo version has changed or image doesn't exist, proceeding with build."
            echo "build_needed=true" >> $GITHUB_ENV
          else
            echo "Hexo version has not changed, skipping build."
            echo "build_needed=false" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        if: env.build_needed == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.build_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        if: env.build_needed == 'true'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hexo:latest
            ${{ secrets.DOCKER_USERNAME }}/hexo:${{ env.HEXO_VERSION }}

      - name: Skip push if no build needed
        if: env.build_needed == 'false'
        run: echo "Skipping build and push as the Hexo version hasn't changed."
